name: Deploy

on:
  push:
    branches: 
    - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build bundle
      run: zip -r deploy.zip . -x '*.git*'
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: nft-runner
        environment_name: Nftrunner-env
        version_label: ${{github.run_number}}
        region: eu-central-1
        deployment_package: deploy.zip
